app <- ShinyDriver$new("../")
app$snapshotInit("mytest")

app$setInputs(genes = c("wwtr1", "yap1", "dap"))
app$setInputs(genes = c("wwtr1", "yap1", "dap", "dcaf8"))
app$setInputs(genes = c("wwtr1", "yap1", "dap", "dcaf8", "sema6e"))
app$setInputs(absrel = "rel")
app$setInputs(type = "median")
app$setInputs(type = "dome")
app$setInputs(type = "128-cell")
app$setInputs(type = "36 hpf")
app$setInputs(type = "24 hpf")
app$setInputs(logScale = "FALSE")
app$setInputs(logScale = "TRUE")
app$setInputs(absrel = "abs")
app$setInputs(logScale = "FALSE")
app$setInputs(logScale = "TRUE")
app$setInputs(genes = c("wwtr1", "yap1", "dap", "dcaf8"))
app$setInputs(genes = c("wwtr1", "yap1", "dap"))
app$setInputs(genes = "wwtr1")
app$setInputs(genes = c("wwtr1", "dcaf8"))
app$setInputs(genes = c("wwtr1", "dcaf8", "ptpn4b"))
app$setInputs(genes = c("wwtr1", "dcaf8", "ptpn4b", "krt97"))
app$setInputs(genes = c("wwtr1", "dcaf8", "ptpn4b", "krt97", "itsn2a"))
app$setInputs(genes = c("wwtr1", "dcaf8", "ptpn4b", "krt97"))
app$setInputs(genes = c("wwtr1", "dcaf8", "ptpn4b"))
app$setInputs(genes = c("wwtr1", "dcaf8"))
app$setInputs(logScale = "FALSE")
app$setInputs(logScale = "TRUE")
app$setInputs(absrel = "rel")
app$setInputs(absrel = "abs")
app$snapshot()
